services:
  php:
    image: php:8.2-apache
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - postgres
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - TINIFY_API_KEY=tHt79fNspyQGYBFBQt9WqXRDVZ1QkwCJ
    command: >
      bash -c "apt-get update && apt-get install -y --no-install-recommends libpq-dev && docker-php-ext-install pdo_pgsql pgsql && a2enmod rewrite expires headers && sed -ri 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf && rm -rf /var/lib/apt/lists/* && apache2-foreground"

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./base:/docker-entrypoint-initdb.d
    networks:
      default:
        aliases:
          - db


volumes:
  pgdata: